# Generated by Django 5.0.6 on 2025-04-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='graphics',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
